<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HIBAIL56180" ignored="0" name="Test" tests="6" failures="2" timestamp="21 Apr 2020 07:58:51 GMT" time="76.603" errors="0">
  <testcase name="runScenario" time="38.889" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="38.913" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="39.9" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at Definition.Test123.userIsAlreadyInTheLoginPage(Test123.java:26)
at ✽.user is already in the login page(file:///E:/NoticeperiodSelenium/cucumberreports/src/main/java/Features/Test123.feature:4)
... Removed 2 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="scenario" time="26.602" classname="RunnerClass.Runner"/>
  <testcase name="scenario" time="27.89" classname="RunnerClass.Runner"/>
  <testcase name="scenario" time="32.848" classname="RunnerClass.Runner">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at Definition.Test123.userIsAlreadyInTheLoginPage(Test123.java:26)
at ✽.user is already in the login page(file:///E:/NoticeperiodSelenium/cucumberreports/src/main/java/Features/Test123.feature:4)
... Removed 2 stack frames]]>
    </failure>
  </testcase> <!-- scenario -->
</testsuite> <!-- Test -->
