<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="HIBAIL56180" name="RunnerClass.Runner" tests="6" failures="2" timestamp="21 Apr 2020 07:58:51 GMT" time="205.042" errors="0">
  <testcase name="runScenario" time="38.889" classname="RunnerClass.Runner"/>
  <testcase name="scenario" time="26.602" classname="RunnerClass.Runner"/>
  <testcase name="runScenario" time="39.900" classname="RunnerClass.Runner">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at Definition.Test123.userIsAlreadyInTheLoginPage(Test123.java:26)
at ✽.user is already in the login page(file:///E:/NoticeperiodSelenium/cucumberreports/src/main/java/Features/Test123.feature:4)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="38.913" classname="RunnerClass.Runner"/>
  <testcase name="scenario" time="27.890" classname="RunnerClass.Runner"/>
  <testcase name="scenario" time="32.848" classname="RunnerClass.Runner">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at Definition.Test123.userIsAlreadyInTheLoginPage(Test123.java:26)
at ✽.user is already in the login page(file:///E:/NoticeperiodSelenium/cucumberreports/src/main/java/Features/Test123.feature:4)
]]>
    </failure>
  </testcase> <!-- scenario -->
</testsuite> <!-- RunnerClass.Runner -->
